#!/bin/bash
# Clone and configure AI Employee on the demo VM
set -euo pipefail

DEMO_DIR="/home/${DEMO_USER:-demo}/ai-employee"
REPO_URL="https://github.com/greeves89/AI-Employee.git"

echo "==> Cloning AI Employee repository..."
git clone --depth=1 "${REPO_URL}" "${DEMO_DIR}"
chown -R "${DEMO_USER:-demo}:${DEMO_USER:-demo}" "${DEMO_DIR}"

echo "==> Writing .env configuration..."
cat > "${DEMO_DIR}/.env" <<EOF
# AI Employee Demo Configuration
# Generated by demo VM provisioner

# Required: Anthropic API key
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-sk-ant-REPLACE-WITH-YOUR-KEY}

# Database (auto-configured)
DB_PASSWORD=$(openssl rand -hex 16)

# Encryption key (auto-generated)
ENCRYPTION_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || openssl rand -base64 32)

# API secret
API_SECRET_KEY=$(openssl rand -hex 32)

# Demo settings
MAX_AGENTS=5
DEFAULT_MODEL=claude-sonnet-4-6
EXTENDED_THINKING=false

# Ports (accessible via NAT port forwarding)
ORCHESTRATOR_PORT=8000
FRONTEND_PORT=3000
EOF

chmod 600 "${DEMO_DIR}/.env"
chown "${DEMO_USER:-demo}:${DEMO_USER:-demo}" "${DEMO_DIR}/.env"

echo "==> Building AI Employee containers..."
cd "${DEMO_DIR}"
sudo -u "${DEMO_USER:-demo}" docker compose build --quiet 2>&1 | tail -5

echo "==> Pulling any remaining images..."
sudo -u "${DEMO_USER:-demo}" docker compose pull --quiet 2>/dev/null || true

echo "==> AI Employee setup complete."
