from fastapi import APIRouter

from app.api import admin, agents, analytics, approval_rules, approvals, audit, auth, computer_use, docker_apps, downloads, erp, event_triggers, features, feedback, health, integrations, knowledge, knowledge_feeds, license as license_api, meeting_rooms, memory, mcp_agent, mcp_msgraph, mcp_servers, notifications, ratings, schedules, skill_marketplace, skills_catalog, tasks, telegram_actions, templates, todos, url_allowlist, user_profiles, version, webhooks, ws, settings

api_router = APIRouter()
api_router.include_router(admin.router)
api_router.include_router(analytics.router)
api_router.include_router(downloads.router)
api_router.include_router(approvals.router)
api_router.include_router(computer_use.router)
api_router.include_router(audit.router)
api_router.include_router(erp.router)
api_router.include_router(auth.router)
api_router.include_router(agents.router)
api_router.include_router(docker_apps.router)
api_router.include_router(event_triggers.router)
api_router.include_router(features.router)
api_router.include_router(feedback.router)
api_router.include_router(health.router)
api_router.include_router(integrations.router)
api_router.include_router(knowledge.router)
api_router.include_router(knowledge_feeds.router)
api_router.include_router(memory.router)
api_router.include_router(mcp_agent.router)
api_router.include_router(mcp_msgraph.router)
api_router.include_router(mcp_servers.router)
api_router.include_router(notifications.router)
api_router.include_router(ratings.router)
api_router.include_router(tasks.router)
api_router.include_router(templates.router)
api_router.include_router(todos.router)
api_router.include_router(schedules.router)
api_router.include_router(skill_marketplace.router)
api_router.include_router(skills_catalog.router)
api_router.include_router(webhooks.router)
api_router.include_router(telegram_actions.router)
api_router.include_router(version.router)
api_router.include_router(ws.router)
api_router.include_router(settings.router)
api_router.include_router(meeting_rooms.router)
api_router.include_router(approval_rules.router)
api_router.include_router(url_allowlist.router)
api_router.include_router(license_api.router)
api_router.include_router(user_profiles.router)
