"""add budget_usd, platform_settings, agent_access, new roles

Revision ID: 2992c8efc2ad
Revises: b4017814d5a5
Create Date: 2026-02-16 19:57:38.399212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2992c8efc2ad'
down_revision: Union[str, None] = 'b4017814d5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('budget_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'budget_usd')
    # ### end Alembic commands ###
