"""add project fields to agent_todos

Revision ID: 41d29f2ad811
Revises: 31bac4710bad
Create Date: 2026-02-18 13:01:14.151970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d29f2ad811'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_todos', sa.Column('project', sa.String(), nullable=True))
    op.add_column('agent_todos', sa.Column('project_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_agent_todos_project'), 'agent_todos', ['project'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_todos_project'), table_name='agent_todos')
    op.drop_column('agent_todos', 'project_path')
    op.drop_column('agent_todos', 'project')
    # ### end Alembic commands ###
