"""add sso fields to user

Revision ID: 8bcc53195fcd
Revises: a1b2c3d4e5f6
Create Date: 2026-02-16 18:31:26.851870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bcc53195fcd'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_agents_user_id'), 'agents', type_='foreignkey')
    op.create_foreign_key(None, 'agents', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('sso_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('sso_subject', sa.String(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('uq_sso_identity', 'users', ['sso_provider', 'sso_subject'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sso_identity', 'users', type_='unique')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'sso_subject')
    op.drop_column('users', 'sso_provider')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_agents_user_id'), 'agents', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
