"""add autonomy_preset_rules table

Revision ID: e286ff01d6fc
Revises: 1f27b810b854
Create Date: 2026-04-23 20:16:55.703252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e286ff01d6fc'
down_revision: Union[str, None] = '1f27b810b854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_memories_embedding'), table_name='agent_memories', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('uq_agent_memory_nullroom_key_value'), table_name='agent_memories', postgresql_where='((room IS NULL) AND (superseded_by IS NULL))')
    op.drop_index(op.f('uq_agent_memory_room_key_value'), table_name='agent_memories', postgresql_where='((room IS NOT NULL) AND (superseded_by IS NULL))')
    op.drop_column('agent_memories', 'embedding')
    op.drop_column('agent_memories', 'value_hash')
    op.drop_index(op.f('ix_agent_memory_links_source'), table_name='agent_memory_links')
    op.drop_index(op.f('ix_agent_memory_links_target'), table_name='agent_memory_links')
    op.drop_index(op.f('ix_agent_memory_tags_tag'), table_name='agent_memory_tags')
    op.alter_column('agent_messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('agent_messages_message_id_key'), 'agent_messages', type_='unique')
    op.drop_index(op.f('ix_agent_messages_from'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_to'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_message_id'), table_name='agent_messages')
    op.create_index(op.f('ix_agent_messages_message_id'), 'agent_messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_agent_messages_from_agent_id'), 'agent_messages', ['from_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_to_agent_id'), 'agent_messages', ['to_agent_id'], unique=False)
    op.drop_column('agent_messages', 'updated_at')
    op.drop_column('agent_messages', 'created_at')
    op.alter_column('agent_skill_assignments', 'assigned_by',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('agent_skill_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_skill_assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_agent_skill_agent'), table_name='agent_skill_assignments')
    op.drop_index(op.f('ix_agent_skill_skill'), table_name='agent_skill_assignments')
    op.drop_constraint(op.f('uq_agent_skill'), 'agent_skill_assignments', type_='unique')
    op.create_index(op.f('ix_agent_skill_assignments_agent_id'), 'agent_skill_assignments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_skill_assignments_skill_id'), 'agent_skill_assignments', ['skill_id'], unique=False)
    op.create_index(op.f('ix_agents_template_id'), 'agents', ['template_id'], unique=False)
    op.alter_column('approval_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('approval_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_approval_rules_active'), table_name='approval_rules')
    op.drop_index(op.f('ix_approval_rules_user_id'), table_name='approval_rules')
    op.drop_column('approval_rules', 'user_id')
    op.drop_index(op.f('ix_knowledge_entries_embedding'), table_name='knowledge_entries', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_knowledge_entries_user_id'), table_name='knowledge_entries')
    op.drop_column('knowledge_entries', 'embedding')
    op.drop_column('knowledge_entries', 'user_id')
    op.drop_index(op.f('ix_knowledge_feed_items_published_at'), table_name='knowledge_feed_items', postgresql_where='(published_at IS NOT NULL)')
    op.alter_column('meeting_rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('meeting_rooms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_meeting_rooms_user_id'), table_name='meeting_rooms')
    op.drop_column('meeting_rooms', 'user_id')
    op.alter_column('skills', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('skills', 'content',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('skills', 'category',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ROUTINE', 'TEMPLATE', 'WORKFLOW', 'PATTERN', 'RECIPE', 'TOOL', name='skillcategory'),
               nullable=False,
               existing_server_default=sa.text("'routine'::character varying"))
    op.alter_column('skills', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'ACTIVE', 'ARCHIVED', name='skillstatus'),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::skillstatus"))
    op.alter_column('skills', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('skills', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('skills', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_index(op.f('ix_skills_status'), table_name='skills')
    op.drop_constraint(op.f('skills_name_key'), 'skills', type_='unique')
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'])
    op.drop_index(op.f('ix_test_runs_started_at'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_status'), table_name='test_runs')
    op.drop_index(op.f('ix_users_last_active_at'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_last_active_at'), 'users', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_test_runs_status'), 'test_runs', ['status'], unique=False)
    op.create_index(op.f('ix_test_runs_started_at'), 'test_runs', ['started_at'], unique=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_unique_constraint(op.f('skills_name_key'), 'skills', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_skills_status'), 'skills', ['status'], unique=False)
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.alter_column('skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('skills', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('skills', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('skills', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'ACTIVE', 'ARCHIVED', name='skillstatus'),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::skillstatus"))
    op.alter_column('skills', 'category',
               existing_type=sa.Enum('ROUTINE', 'TEMPLATE', 'WORKFLOW', 'PATTERN', 'RECIPE', 'TOOL', name='skillcategory'),
               type_=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'routine'::character varying"))
    op.alter_column('skills', 'content',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('skills', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.add_column('meeting_rooms', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_meeting_rooms_user_id'), 'meeting_rooms', ['user_id'], unique=False)
    op.alter_column('meeting_rooms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('meeting_rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_knowledge_feed_items_published_at'), 'knowledge_feed_items', ['published_at'], unique=False, postgresql_where='(published_at IS NOT NULL)')
    op.add_column('knowledge_entries', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('knowledge_entries', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_knowledge_entries_user_id'), 'knowledge_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_embedding'), 'knowledge_entries', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('approval_rules', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_approval_rules_user_id'), 'approval_rules', ['user_id'], unique=False)
    op.create_index(op.f('ix_approval_rules_active'), 'approval_rules', ['is_active'], unique=False)
    op.alter_column('approval_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('approval_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_agents_template_id'), table_name='agents')
    op.drop_index(op.f('ix_agent_skill_assignments_skill_id'), table_name='agent_skill_assignments')
    op.drop_index(op.f('ix_agent_skill_assignments_agent_id'), table_name='agent_skill_assignments')
    op.create_unique_constraint(op.f('uq_agent_skill'), 'agent_skill_assignments', ['agent_id', 'skill_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_agent_skill_skill'), 'agent_skill_assignments', ['skill_id'], unique=False)
    op.create_index(op.f('ix_agent_skill_agent'), 'agent_skill_assignments', ['agent_id'], unique=False)
    op.alter_column('agent_skill_assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_skill_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_skill_assignments', 'assigned_by',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.add_column('agent_messages', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('agent_messages', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_agent_messages_to_agent_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_from_agent_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_message_id'), table_name='agent_messages')
    op.create_index(op.f('ix_agent_messages_message_id'), 'agent_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_to'), 'agent_messages', ['to_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_from'), 'agent_messages', ['from_agent_id'], unique=False)
    op.create_unique_constraint(op.f('agent_messages_message_id_key'), 'agent_messages', ['message_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('agent_messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_agent_memory_tags_tag'), 'agent_memory_tags', ['tag'], unique=False)
    op.create_index(op.f('ix_agent_memory_links_target'), 'agent_memory_links', ['target_id'], unique=False)
    op.create_index(op.f('ix_agent_memory_links_source'), 'agent_memory_links', ['source_id'], unique=False)
    op.add_column('agent_memories', sa.Column('value_hash', sa.VARCHAR(length=32), sa.Computed("md5(COALESCE(content, ''::text))", persisted=True), autoincrement=False, nullable=True))
    op.add_column('agent_memories', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index(op.f('uq_agent_memory_room_key_value'), 'agent_memories', ['agent_id', 'room', 'key', 'value_hash'], unique=True, postgresql_where='((room IS NOT NULL) AND (superseded_by IS NULL))')
    op.create_index(op.f('uq_agent_memory_nullroom_key_value'), 'agent_memories', ['agent_id', 'key', 'value_hash'], unique=True, postgresql_where='((room IS NULL) AND (superseded_by IS NULL))')
    op.create_index(op.f('ix_agent_memories_embedding'), 'agent_memories', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
