"""add parent_task_id for subtask hierarchies

Revision ID: f2da25b5ed7d
Revises: p0j1k2l3m4n5
Create Date: 2026-04-07 11:02:49.688566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2da25b5ed7d'
down_revision: Union[str, None] = 'p0j1k2l3m4n5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_memories_embedding'), table_name='agent_memories', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('agent_memories', 'embedding')
    op.alter_column('agent_messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_agent_messages_from'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_to'), table_name='agent_messages')
    op.create_index(op.f('ix_agent_messages_from_agent_id'), 'agent_messages', ['from_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_to_agent_id'), 'agent_messages', ['to_agent_id'], unique=False)
    op.drop_column('agent_messages', 'created_at')
    op.drop_column('agent_messages', 'updated_at')
    op.create_index(op.f('ix_agents_template_id'), 'agents', ['template_id'], unique=False)
    op.alter_column('approval_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('approval_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_approval_rules_active'), table_name='approval_rules')
    op.drop_index(op.f('ix_approval_rules_user_id'), table_name='approval_rules')
    op.drop_column('approval_rules', 'user_id')
    op.drop_index(op.f('ix_knowledge_entries_embedding'), table_name='knowledge_entries', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_knowledge_entries_user_id'), table_name='knowledge_entries')
    op.drop_column('knowledge_entries', 'embedding')
    op.drop_column('knowledge_entries', 'user_id')
    op.alter_column('meeting_rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('meeting_rooms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_meeting_rooms_user_id'), table_name='meeting_rooms')
    op.drop_column('meeting_rooms', 'user_id')
    op.add_column('tasks', sa.Column('parent_task_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'])
    op.drop_index(op.f('ix_test_runs_started_at'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_status'), table_name='test_runs')
    op.drop_index(op.f('ix_users_last_active_at'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_last_active_at'), 'users', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_test_runs_status'), 'test_runs', ['status'], unique=False)
    op.create_index(op.f('ix_test_runs_started_at'), 'test_runs', ['started_at'], unique=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_column('tasks', 'parent_task_id')
    op.add_column('meeting_rooms', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_meeting_rooms_user_id'), 'meeting_rooms', ['user_id'], unique=False)
    op.alter_column('meeting_rooms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('meeting_rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column('knowledge_entries', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('knowledge_entries', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_knowledge_entries_user_id'), 'knowledge_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_embedding'), 'knowledge_entries', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('approval_rules', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_approval_rules_user_id'), 'approval_rules', ['user_id'], unique=False)
    op.create_index(op.f('ix_approval_rules_active'), 'approval_rules', ['is_active'], unique=False)
    op.alter_column('approval_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('approval_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_agents_template_id'), table_name='agents')
    op.add_column('agent_messages', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('agent_messages', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_agent_messages_to_agent_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_from_agent_id'), table_name='agent_messages')
    op.create_index(op.f('ix_agent_messages_to'), 'agent_messages', ['to_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_from'), 'agent_messages', ['from_agent_id'], unique=False)
    op.alter_column('agent_messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('agent_memories', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_agent_memories_embedding'), 'agent_memories', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
