"""switch embedding dimension from 1536 (OpenAI) to 1024 (bge-m3 local model)

Revision ID: p0j1k2l3m4n5
Revises: o9i0j1k2l3m4
Create Date: 2026-04-05

We're moving from OpenAI text-embedding-3-small (1536 dim, cloud, paid) to
BAAI/bge-m3 (1024 dim, local, free, multilingual). Existing embeddings are
dropped — they'll be regenerated by the backfill job.
"""

from alembic import op

revision = "p0j1k2l3m4n5"
down_revision = "o9i0j1k2l3m4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Drop old indexes + columns (they may or may not exist depending on the environment)
    op.execute("DROP INDEX IF EXISTS ix_agent_memories_embedding")
    op.execute("DROP INDEX IF EXISTS ix_knowledge_entries_embedding")
    op.execute("ALTER TABLE agent_memories DROP COLUMN IF EXISTS embedding")
    op.execute("ALTER TABLE knowledge_entries DROP COLUMN IF EXISTS embedding")

    # Recreate with 1024 dimensions (bge-m3)
    op.execute("ALTER TABLE agent_memories ADD COLUMN embedding vector(1024)")
    op.execute("ALTER TABLE knowledge_entries ADD COLUMN embedding vector(1024)")
    op.execute(
        "CREATE INDEX ix_agent_memories_embedding "
        "ON agent_memories USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_knowledge_entries_embedding "
        "ON knowledge_entries USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_agent_memories_embedding")
    op.execute("DROP INDEX IF EXISTS ix_knowledge_entries_embedding")
    op.execute("ALTER TABLE agent_memories DROP COLUMN IF EXISTS embedding")
    op.execute("ALTER TABLE knowledge_entries DROP COLUMN IF EXISTS embedding")
    op.execute("ALTER TABLE agent_memories ADD COLUMN embedding vector(1536)")
    op.execute("ALTER TABLE knowledge_entries ADD COLUMN embedding vector(1536)")
